### ISSUE TITLE
Clear messaging when raygun cannot use the target directory

### ISSUE THREAD

**Issue by bunnymatic** [carbonfive/raygun#128]
We had a initial commit in github.  i cloned the project into `my_dir` then tried to run raygun and got

```
sed: RE error: illegal byte sequence
/Users/jon/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/raygun-1.0.0/lib/raygun/raygun.rb:273:in `shell': find . -type f -print | xargs sed -i '' 's/AppPrototype/Hood/g' failed with status 1. (RuntimeError)
	from /Users/jon/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/raygun-1.0.0/lib/raygun/raygun.rb:117:in `block (2 levels) in rename_new_app'
	from /Users/jon/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/raygun-1.0.0/lib/raygun/raygun.rb:116:in `each'
	from /Users/jon/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/raygun-1.0.0/lib/raygun/raygun.rb:116:in `block in rename_new_app'
	from /Users/jon/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/raygun-1.0.0/lib/raygun/raygun.rb:110:in `chdir'
	from /Users/jon/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/raygun-1.0.0/lib/raygun/raygun.rb:110:in `rename_new_app'
	from /Users/jon/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/raygun-1.0.0/bin/raygun:16:in `<top (required)>'
	from /Users/jon/.rbenv/versions/2.1.1/bin/raygun:23:in `load'
	from /Users/jon/.rbenv/versions/2.1.1/bin/raygun:23:in `<main>'
```

more later...

**Comment by christiannelson** [comment]
```rails new``` also will not create an app in an existing directory if it has anything in it. Though, it does provide a meaningful error message. :)

**Comment by bunnymatic** [comment]
i'd be happy with an error message that made sense.

**Comment by christiannelson** [comment]
When the target directory exists and is not empty, provide a useful message. 

https://github.com/carbonfive/raygun/blob/master/lib/raygun/raygun.rb#L36 should be doing that, and it seems to be working for me locally, but the comment above suggests that it does not catch things in every situation.

**Comment by bunnymatic** [comment]
I'll give it a go.  This ticket is old.  Maybe things have changed.

**Comment by bunnymatic** [comment]
Looks good to me....

```
% mkdir existing_dir/
% cd existing_dir/
% git init .
Initialized empty Git repository in /Users/jon/projects/existing_dir/.git/
% touch README.md
% cd ..
% raygun existing_dir
Misfire! The target directory isn't empty... aim elsewhere.
% raygun existing_dir/
Misfire! The target directory isn't empty... aim elsewhere.
```
